config/routes.rb
Spotmine::Application.routes.draw do
  resources :bids

  resources :auctions
  
  match "browse_auctions" => "auctions#active_auctions", :as => :auction_listings

  resources :spot_listings
  match "browse_listings" => "spot_listings#open_listings", :as => :browse_listings
  match "listing/:id/lender/:lender_id" => "spot_listings#complete_loan", :as => :complete_loan

  match "login" => "session#new", :as => :login
  
  match "logout" => "session#destroy", :as => :logout
  
  match "session/create" => "session#create", :as => :create_session

  resources :users
  
  match "dashboard" => "users#dashboard", :as => :user_dashboard

  root :to => 'marketing#home'

end

app/models/spot_listing.rb
class SpotListing < ActiveRecord::Base
  belongs_to :user
end

app/controllers/spot_listings_controller.rb
class SpotListingsController < ApplicationController
  # GET /spot_listings
  # GET /spot_listings.json
  def index
    @spot_listings = SpotListing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spot_listings }
    end
  end

  # GET /spot_listings/1
  # GET /spot_listings/1.json
  def show
    @spot_listing = SpotListing.find(params[:id])
    @user = @spot_listing.user
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spot_listing }
    end
  end

  # GET /spot_listings/new
  # GET /spot_listings/new.json
  def new
    @spot_listing = SpotListing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spot_listing }
    end
  end

  # GET /spot_listings/1/edit
  def edit
    @spot_listing = SpotListing.find(params[:id])
  end

  # POST /spot_listings
  # POST /spot_listings.json
  def create
    @spot_listing = current_user.spot_listings.build(params[:spot_listing])
    @spot_listing.completed = false
    respond_to do |format|
      if @spot_listing.save
        format.html { redirect_to user_dashboard_url, notice: 'Your listing has been successfully created' }
        format.json { render json: @spot_listing, status: :created, location: @spot_listing }
      else
        format.html { render action: "new" }
        format.json { render json: @spot_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spot_listings/1
  # PUT /spot_listings/1.json
  def update
    @spot_listing = SpotListing.find(params[:id])

    respond_to do |format|
      if @spot_listing.update_attributes(params[:spot_listing])
        format.html { redirect_to @spot_listing, notice: 'Spot listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @spot_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spot_listings/1
  # DELETE /spot_listings/1.json
  def destroy
    @spot_listing = SpotListing.find(params[:id])
    @spot_listing.destroy

    respond_to do |format|
      format.html { redirect_to spot_listings_url }
      format.json { head :no_content }
    end
  end
  
  def open_listings
    @spot_listings= SpotListing.where(:completed => false)
    respond_to do |format|
      format.html
    end
  end
  
  def complete_loan
    @spot_listing = SpotListing.find(params[:id])
    @lender = User.find(params[:lender_id])
    @borrower = @spot_listing.user
    
    @spot_listing.lender_id = @lender.id
    @spot_listing.completed = true
    logger.error @borrower.gem_balance
    logger.error @spot_listing
    @borrower.gem_balance = @borrower.gem_balance - @spot_listing.amount.to_i
    @lender.gem_balance = @lender.gem_balance + @spot_listing.amount.to_i
    respond_to do |format|
      if @spot_listing.save && @borrower.save && @lender.save
        format.html {redirect_to user_dashboard_url, notice: 'Success! Money has been sent and gems added to your account'}
      else
        format.html {redirect_to user_dashboard_url, notice: 'Something went wrong, please contact us at help@spotmine.com'}
      end
    end
  end
end

app/helpers/spot_listings_helper.rb
module SpotListingsHelper
end

app/views/spot_listings/_account_form.html.erb
<div class="lines">
	<p class="center">Please login or sign up <%= header %></p>
</div>
<div class="container extrapadding center">
			<%= link_to "Login", login_path, :class => "round-button blue"%>
			<%= link_to "Sign Up", new_user_path, :class => "round-button blue"%>
</div>

app/views/spot_listings/_form.html.erb
				<%= form_for(@spot_listing) do |f| %>
				  <% if @spot_listing.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= pluralize(@spot_listing.errors.count, "error") %> prohibited this spot_listing from being saved:</h2>

				      <ul>
				      <% @spot_listing.errors.full_messages.each do |msg| %>
				        <li><%= msg %></li>
				      <% end %>
				      </ul>
				    </div>
				  <% end %>

				  <div class="field">
				    <%= f.label :title %><br />
				    <%= f.text_area :title %>
				  </div>
				  <div class="field">
				    <%= f.label :description %><br />
				    <%= f.text_area :description %>
				  </div>
				  <div class="field">
				    <%= f.label :amount %><br />
				    <%= f.text_field :amount %>
				  </div>
				  <div class="actions">
				    <%= f.submit %>
				  </div>
				<% end %>

app/views/spot_listings/edit.html.erb
<h1>Editing spot_listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @spot_listing %> |
<%= link_to 'Back', spot_listings_path %>

app/views/spot_listings/index.html.erb
<h1>Listing spot_listings</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spot_listings.each do |spot_listing| %>
  <tr>
    <td><%= spot_listing.title %></td>
    <td><%= spot_listing.description %></td>
    <td><%= spot_listing.amount %></td>
    <td><%= link_to 'Show', spot_listing %></td>
    <td><%= link_to 'Edit', edit_spot_listing_path(spot_listing) %></td>
    <td><%= link_to 'Destroy', spot_listing, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Spot listing', new_spot_listing_path %>

app/views/spot_listings/new.html.erb
<div class="container clearfix">
	<div id="main-holder" role="main">	
		<section id="main-content">
	    	<div class="columns">
	            <div class="block clearfix">
	            <header class="section-headline">
	                <h3><span class="blue">Ask for a spot</span></h3>
	            </header>
				<% if current_user %>
					<%= render 'form' %>
				<% else %>
				<div class="full_column">
					<div class="container">
						<%= render 'account_form', :header => "to ask for a spot"%>
					</div>
				</div>
				<% end %>
				</div>
			</div>
		</sectin>
	</div>
</div>

app/views/spot_listings/open_listings.html.erb
<div class="container clearfix">
	<div id="main-holder" role="main">	
		<section id="main-content">
	    	<div class="columns">
	            <div class="block clearfix">
            
	            <header class="section-headline">
	                <h3>Lend <span class="blue">Money</span></h3>
	            </header>

	            <% @spot_listings.each do |spot_listing| %>
	            	<div class="full_column">
	                	<header class="box-headline">
		                    <h4><%= spot_listing.title %></h4>
		                </header>
                
		                <div class="content">
		                    <div class="one_half">
		                    	<h3>Amount Needed: <%= number_to_currency(spot_listing.amount, :unit => "$")%></h3>
		                        <p><%= spot_listing.description %></p>
		                    </div>
		                    <div class="one_half last">
								<h3>Borrower: <%= spot_listing.user.first_name %></h3>
								<p><%= link_to "More Info", spot_listing, :class => "round-button blue" %></p>
							</div>
						</div>
					</div>
					<% end %>
				</div>
			</div>
		</section>
	</div>
</div>

app/views/spot_listings/show.html.erb
<div class="container clearfix">
	<div id="main-holder" role="main">	
		<section id="main-content">
	    	<div class="columns">
	            <div class="block clearfix">
	            <header class="section-headline">
	                <h3>Spot <span class="blue"><%= @user.first_name %></span></h3>
	            </header>
	            	<div class="full_column">
	                	<header class="box-headline">
		                    <h4><%= @spot_listing.title %></h4>
		                </header>
               
		                <div class="content">
		                    <div class="one_half">
		                    	<h3>Amount Needed: <%= number_to_currency(@spot_listing.amount, :unit => "$")%></h3>
		                        <p><%= @spot_listing.description %></p>
		                    </div>
                   
		                    <div class="one_half last">
								<h3>Borrower: <%= @user.first_name %> <%= @user.last_name %></h3>
								<div class="one_half">
									<%= image_tag @user.picture.url(:thumb) %>
								</div>
								<div class="one_half last">
									<%= @user.description %>
								</div>
							</div>
						</div>
					</div>
					<div class="full_column">
						<div class="container">
							<% if current_user %>
								<% if current_user.id != @spot_listing.user.id %>
								<div class="lines">
									<% if @spot_listing.completed == false %>
										<%= link_to "Spot this person now!", complete_loan_path(@spot_listing.id, current_user.id), :class => "round-button blue"%>
									<% end %>
								<% end%>
							</div>
							<% else %>
								<%= render 'account_form', :header => "in order to spot money"%>
							<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</div>
</div>