config/routes.rb
Spotmine::Application.routes.draw do
  resources :bids

  resources :auctions
  
  match "browse_auctions" => "auctions#active_auctions", :as => :auction_listings

  resources :spot_listings
  match "browse_listings" => "spot_listings#open_listings", :as => :browse_listings
  match "listing/:id/lender/:lender_id" => "spot_listings#complete_loan", :as => :complete_loan

  match "login" => "session#new", :as => :login
  
  match "logout" => "session#destroy", :as => :logout
  
  match "session/create" => "session#create", :as => :create_session

  resources :users
  
  match "dashboard" => "users#dashboard", :as => :user_dashboard

  root :to => 'marketing#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_uniqueness_of :email, :on => :create
  attr_accessible :email, :password, :password_confirmation, :first_name, :last_name, :picture, :description
  has_attached_file :picture, :styles => { :medium => "300x300!", :thumb => "90x90!" }, :storage => :s3, :bucket => 'spotmine', :s3_credentials => { :access_key_id => 'AKIAJCFMJMYU4L3MBM5Q', :secret_access_key => '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'}

  has_many :spot_listings
  has_many :auctions
  has_many :bids
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to user_dashboard_url, notice: 'Welcome to spotmine!' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  def dashboard
    @user = current_user
    @lended = SpotListing.where(:lender_id => @user.id)
    @auctions = @user.auctions
    @won = Auction.where(:winner_id => @user.id)
    respond_to do |format|
      format.html
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="container clearfix">
	<div id="main-holder" role="main">	
		<section id="main-content">
	    	<div class="columns">
	            <div class="block clearfix">
	            <header class="section-headline">
	                <h3><span class="blue">Create Account</span></h3>
	            </header>
	            <div class="container">
					<%= form_for(@user) do |f| %>
					  <% if @user.errors.any? %>
					    <div id="error_explanation">
					      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

					      <ul>
					      <% @user.errors.full_messages.each do |msg| %>
					        <li><%= msg %></li>
					      <% end %>
					      </ul>
					    </div>
					  <% end %>
					  <div class="field">
					    <%= f.label :email %><br />
					    <%= f.text_field :email %>
					  </div>
					  <div class="field">
					    <%= f.label :password %><br />
					    <%= f.password_field :password %>
					  </div>
					  <div class="field">
					    <%= f.label :password_confirmation %><br />
					    <%= f.password_field :password_confirmation %>
					  </div>
					  <div class="field">
					    <%= f.label :first_name %><br />
					    <%= f.text_field :first_name %>
					  </div>
					  <div class="field">
					    <%= f.label :last_name %><br />
					    <%= f.text_field :last_name %>
					  </div>
					  <div class="field">
						<%= f.label "Description of yourself" %>
						<%= f.text_area :description %>
					  </div>
					  <div class="field">
						<%= f.label :picture %>
						<%= f.file_field :picture %>
					  </div>
					  <div class="actions">
					    <%= f.submit "Sign Up"%>
					  </div>
					<% end %>
				</div>
			</div>
		</section>
	</div>
</div>

app/views/users/dashboard.html.erb
<div class="container clearfix">
	<div id="main-holder" role="main">	
		<section id="main-content">
	    	<div class="columns">
	            <div class="block clearfix">
	            <header class="section-headline">
	                <h3><span class="blue">Dashboard</span></h3>
	            </header>
					<% if notice %>
					<div class="notification-box success">
						<%= notice %>
					</div>
				    <% end %>
	
	            	<div class="full_column">
	                	<header class="box-headline">
		                    <h4>Welcome back <%= @user.first_name %></h4>
		                </header>
		                <div class="content">
		                    You're current gem balance is <%= @user.gem_balance %>
						</div>
					</div>
					<div class="full_column">
						<header class="box-headline">
		                    <h4>Auctions you have won</h4>
		                </header>
		                <div class="content">
							 <% @won.each do |w| %>
									<div class="one_half">
										<%= a.title %>
									</div>
									<div class="one_half last">
										<%= link_to "View Auction", auction_path(w), :class => "styled-button blue"%>
									</div>
								<% end %>
						</div>
					</div>
					<div class="full_column">
	                	<header class="box-headline">
		                    <h4>Auctions you have created</h4>
		                </header>
		                <div class="content">
		                    <% @auctions.each do |a| %>
								<div class="one_half">
									<%= a.title %>
								</div>
								<div class="one_half last">
									<%= link_to "View Auction", auction_path(a), :class => "styled-button blue"%>
								</div>
							<% end %>
							<div class="one_half">
								<%= link_to "Create New Auction", new_auction_path, :class => "styled-button blue"%>
							</div>
						</div>
					</div>
					<div class="full_column">
						<header class="box-headline">
		                    <h4>Spots you have asked for</h4>
		                </header>
						<div class="content">
							<% @user.spot_listings.each do |listing| %>
								<div class="one_half">
									<%= listing.title %>
								</div>
								<div class="one_half last">
									<%= link_to "view listing", spot_listing_path(listing), :class => "styled-button blue" %>
								</div>
							<% end %>
								<div class="one_half">
									<%= link_to "Ask for a spot!", new_spot_listing_path, :class => "styled-button blue" %>
								</div>
						</div>
					</div>
					<div class="full_column">
						<header class="box-headline">
		                    <h4>People you have spotted</h4>
		                </header>
						<div class="content">
							<% @lended.each do |loan| %>
								<div class="one_half">
									<%= loan.user.first_name %> - <%= loan.title%>
								</div>
								<div class="one_half last">
									<%= link_to "view listing", spot_listing_path(loan), :class => "styled-button blue"%>
								</div>		
							<% end %>
								<div class="one_half">
									<%= link_to "Browse Spot Listings", browse_listings_path, :class => "styled-button blue" %>
								</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Password digest</th>
    <th>Gem balance</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <td><%= user.password_digest %></td>
    <td><%= user.gem_balance %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Gem balance:</b>
  <%= @user.gem_balance %>
</p>

<p>
  <%= image_tag @user.picture.url(:medium) %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>