config/routes.rb
Spotmine::Application.routes.draw do
  resources :bids

  resources :auctions
  
  match "browse_auctions" => "auctions#active_auctions", :as => :auction_listings

  resources :spot_listings
  match "browse_listings" => "spot_listings#open_listings", :as => :browse_listings
  match "listing/:id/lender/:lender_id" => "spot_listings#complete_loan", :as => :complete_loan

  match "login" => "session#new", :as => :login
  
  match "logout" => "session#destroy", :as => :logout
  
  match "session/create" => "session#create", :as => :create_session

  resources :users
  
  match "dashboard" => "users#dashboard", :as => :user_dashboard

  root :to => 'marketing#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  	<meta charset="utf-8">
	<title>SpotMine</title>
	<meta name="description" content="">
  	<meta name="author" content="">
	<!-- Mobile viewport optimized: j.mp/bplateviewport -->
	<meta name="viewport" content="width=device-width,initial-scale=1">
  	<%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
</head>
<body id="top">
	<header id="main">

	<div class="container">
	  <div class="logo">
			
	      <%= link_to image_tag("SpotMineLogo.png"), root_url %>
	      <div class="lines"><p class="subtitle">Zero Interest Loans</p></div>
	  </div>    
	</div><!-- end of .logo -->

	<!-- Primary navigation -->
	<nav id="main-nav">
	<div class="container">
	  <ul class="sf-menu">
	      <li><%= link_to "Home", root_url%></li>
	      <li><%= link_to "Lend Money", browse_listings_path %>
	      </li>
	      <li><%= link_to "Borrow Money", new_spot_listing_path %>
	      </li>
	      <li><%= link_to "Social Interest Auctions", auction_listings_path %></li>
		  <% if current_user %>
		  <li><%= link_to "Dashboard", user_dashboard_path %></li>
		  <li><%= link_to "Logout", logout_path %></li>
		  <% else %>
		  <li><%= link_to "Login", login_path %></li>
		  <li><%= link_to "Sign Up", new_user_path %></li>
		  <% end %>
	  </ul>
	</div>    
	</nav>
	<!-- End Primary navigation -->

	<div class="clearfix"></div>
	</header><!--! end of header -->
	<%= yield %>
	<div class="footer clearfix">
		<div class="container">
		</div> <!-- end of #container -->     
	</div>
<!-- end of footer -->
<p id="back-top"><a href="#top"><span></span></a></p>
</body>
</html>